Making the reparametrization type an argument.
Also exposing the attenuation coefficient exponent for testing. Now
there are two types of reparametrization Box and PolyK. Box is the old
method with box filter. PolyK is one with 1-(n/n*)^k (for n<n*)
attenuation coefficient. In case of PolyK, k is a float and can be
smaller or greater than one. Large k gives a filter very similar to
the Box case.

diff --git a/test/makefile b/test/makefile
--- a/test/makefile
+++ b/test/makefile
@@ -2,8 +2,6 @@ ifndef VES3D_DIR
 $(error "$${VES3D_DIR} environment variable is not set.")
 endif
 
-RUNEXE = 0
-
 # include rules and flag for compiler/host
 VES3D_MKDIR ?= ${VES3D_DIR}/makefile.in.files
 include ${VES3D_MKDIR}/makefile.in
@@ -18,7 +16,6 @@ TEST = 	ArrayTest.exe			\
 	EvolveSurfaceTest.exe		\
 	EvolveSurfaceTestMultThread.exe \
 	LoggerTest.exe			\
-	MemoryManagerTest.exe		\
 	MovePoleTest.exe		\
 	ParametersTest.exe		\
 	ParsingTest.exe			\
@@ -32,6 +29,7 @@ TEST = 	ArrayTest.exe			\
         SurfaceTest.exe			\
         Tr1Test.exe			\
         VectorsTest.exe			\
+#	MemoryManagerTest.exe		\
 
 ifeq (${VES3D_USE_PVFMM},yes)
   TEST += PVFMMInterfaceTest.exe	\
@@ -47,6 +45,12 @@ ifeq (${VES3D_DEBUG},yes)
   TEST +=BenchmarkInterfacialVel.exe
 endif
 
+RUNEXE   = 0
+FAILFILE = test_results.txt
+EXECLOG  = tests.log
+EXECNAME =
+SHELL = /bin/bash
+
 all: ${TEST}
 
 #build the dependencies for next time. We can have a rule for
@@ -57,15 +61,30 @@ all: ${TEST}
 	@if [ "${RUNEXE}" -ne "0" ]; then ./$@; fi
 
 clean:
-	-${RM} *.o *.exe *.out *.d *.${VES3D_CHKEXT}
+	-${RM} *.o *.out *.d *.${VES3D_CHKEXT} ${FAILFILE}  ${EXECLOG}
+
+distclean:
+	${MAKE} clean
+	-${RM} *.exe
 
 check:  ${TEST}
 	${MAKE} run
 
 run:
-	@for exec in *.exe; do echo "Running " $$exec; ./$$exec;sleep 1;done
+	@echo -- TEST TIME: `date` --------------- >> ${EXECLOG}
+	tail -1 ${EXECLOG} >> ${FAILFILE}
+	@for exec in *.exe; do					\
+	    echo Running $$exec;				\
+	    ${MAKE} EXECNAME=$$exec run-exec;			\
+	    sleep 1;						\
+	done;
+	@tail -20 ${FAILFILE}
+
+run-exec:
+	./${EXECNAME} | tee -a ${EXECLOG}; test $$? -eq 0 || echo "${EXECNAME} failed" >> ${FAILFILE}
 
 .PHONY: clean check run
 .SECONDARY:
+.SHELLFLAGS = -o pipefail
 
 -include $(TEST:.exe=.d)
